#!/usr/bin/env bash
#
#   dev/pin.sh [COMPONENT...]        (make pin)
#
# Records the sha256 of every artifact dev/versions.env names, for every
# platform the dev image and CI run on, in dev/checksums/<COMPONENT>.sha256.
# Run it after changing a version, and commit both files: the installers refuse
# an artifact whose checksum is not recorded, or does not match.
#
# Components: tmux fzf fzf-old bash-old shellcheck actionlint hadolint lychee
# rustup bash-macos libevent utf8proc jemalloc (default: all).  Platforms:
# linux amd64 and arm64 for everything the image runs (amd64 is this VPS's,
# CI's and an Intel Mac's Docker; arm64 an Apple Silicon Mac's); macOS amd64
# and arm64 for fzf, which CI's macOS job installs, and for shellcheck, which
# tests/lint.sh fetches on a Mac.  The macOS job's sources (bash-macos and
# tmux's three libraries) have one tarball for every platform.
#
# A checksum recorded here is trust on first use: it pins what the URL served
# when this ran.  Where a project publishes its own sha256 (fzf, actionlint,
# hadolint, lychee, rustup), the download must match that too, or nothing is
# recorded.  Versions are read from the file only, never from the environment.
#
# bash 3.2 or newer, curl, and sha256sum or shasum: runs on Linux and macOS.

set -euo pipefail
# shellcheck source=dev/install/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/install/lib.sh"

ALL="tmux fzf fzf-old bash-old shellcheck actionlint hadolint lychee rustup bash-macos libevent utf8proc jemalloc"
LINUX="linux:amd64 linux:arm64"

from_file() {
  local val
  val=$(sed -n "s/^$1=//p" "$IMUX_DEV/versions.env" | tail -n 1)
  [ -n "$val" ] || die "no $1 in dev/versions.env"
  printf '%s\n' "$val"
}

# What one component pins: lines of "VERSION OS ARCH" (OS and ARCH "-" for a
# source tarball).
targets() {
  local v p
  case $1 in
    tmux)       echo "$(from_file TMUX_VERSION) - -" ;;
    bash-old)   for v in $(items "$(from_file OLD_BASH_VERSIONS)"); do echo "$v - -"; done ;;
    fzf)        for p in $LINUX darwin:amd64 darwin:arm64; do echo "$(from_file FZF_VERSION) ${p%:*} ${p#*:}"; done ;;
    fzf-old)    for v in $(items "$(from_file OLD_FZF_VERSIONS)"); do
                  for p in $LINUX; do echo "$v ${p%:*} ${p#*:}"; done; done ;;
    shellcheck) for p in $LINUX darwin:amd64 darwin:arm64; do
                  echo "$(from_file SHELLCHECK_VERSION) ${p%:*} ${p#*:}"; done ;;
    actionlint) for p in $LINUX; do echo "$(from_file ACTIONLINT_VERSION) ${p%:*} ${p#*:}"; done ;;
    hadolint)   for p in $LINUX; do echo "$(from_file HADOLINT_VERSION) ${p%:*} ${p#*:}"; done ;;
    lychee)     for p in $LINUX; do echo "$(from_file LYCHEE_VERSION) ${p%:*} ${p#*:}"; done ;;
    rustup)     for p in $LINUX; do echo "$(from_file RUSTUP_INIT_VERSION) ${p%:*} ${p#*:}"; done ;;
    bash-macos) v=$(from_file MACOS_BASH_VERSION)
                echo "${v%.*} - -"
                n=1; while [ "$n" -le "${v##*.}" ]; do echo "${v%.*}.$n - -"; n=$((n + 1)); done ;;
    libevent)   echo "$(from_file LIBEVENT_VERSION) - -" ;;
    utf8proc)   echo "$(from_file UTF8PROC_VERSION) - -" ;;
    jemalloc)   echo "$(from_file JEMALLOC_VERSION) - -" ;;
    *) die "no component '$1' (there are: $ALL)" ;;
  esac
}

# The project's own sha256 for BASENAME in the sums file at URL, if it lists it.
upstream_sum() {
  curl -fsSL --retry 3 --connect-timeout 30 "$1" 2>/dev/null | awk -v b="$2" '
    NF == 1 { print $1; exit }
    { f = $NF; sub(/^\*/, "", f); sub(/^\.\//, "", f); if (f == b) { print $1; exit } }'
}

scratch
# shellcheck disable=SC2086  # $ALL is a space-separated list
[ $# -gt 0 ] || set -- $ALL
for comp in "$@"; do
  targets "$comp" > /dev/null   # an unknown component fails before any download
done
for comp in "$@"; do
  out="$IMUX_SCRATCH/$comp.sha256"
  printf '# %s: generated by dev/pin.sh from dev/versions.env -- do not edit\n' "$comp" > "$out"
  targets "$comp" | while read -r v os arch; do
    [ "$os" = - ] && os="" arch=""
    spec=$(artifact "$comp" "$v" "$os" "$arch")
    name=$(printf '%s\n' "$spec" | sed -n 1p)
    urls=$(printf '%s\n' "$spec" | sed -n 2p)
    sums=$(printf '%s\n' "$spec" | sed -n 3p)
    # shellcheck disable=SC2086  # $urls is a space-separated list of URLs
    download "$IMUX_SCRATCH/$name" $urls || die "could not download $name"
    got=$(sha256_of "$IMUX_SCRATCH/$name")
    note="no published sha256 to compare"
    if [ "$sums" != - ]; then
      first=${urls%% *}
      up=$(upstream_sum "$sums" "${first##*/}") || die "could not fetch $sums"
      [ -n "$up" ] || die "$sums does not list ${first##*/}"
      [ "$up" = "$got" ] || die "$name: downloaded sha256 $got, but $sums says $up"
      note="matches the published sha256"
    fi
    printf '%s  %s\n' "$got" "$name" >> "$out"
    printf '  %-48s %s\n' "$name" "$note"
    rm -f "$IMUX_SCRATCH/$name"
  done
  mkdir -p "$IMUX_DEV/checksums"
  mv "$out" "$IMUX_DEV/checksums/$comp.sha256"
  echo "wrote dev/checksums/$comp.sha256"
done
